name: Lighthouse Audit
on: push

jobs:
  audit:
    runs-on: ubuntu-latest
    steps:
    - name: Audit Marco Ibarra Website
      uses: jakejarvis/lighthouse-action@master
      with:
        url: 'http://maibarra.github.io/'
    - name: Upload results Artifact
      uses: actions/upload-artifact@master
      with:
        name: report
        path: './report'
